"""PostCallSummaryRepository — PostgreSQL persistence for post-call sales summaries.

Stores structured post-call summaries generated by generate_post_call_summary()
for CRM integration, analytics, and supervisor review.

Architecture: VoiceOS Phase 3 Production Action Layer.
"""

from __future__ import annotations

import json
from typing import Any

from .base import BaseRepository

_TABLE = "call_summaries"

_CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS call_summaries (
    call_id         TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    customer_id     TEXT NOT NULL,
    lead_stage      TEXT,
    lead_temperature TEXT,
    qualification_score INTEGER,
    requirements    JSONB,
    conversation    JSONB,
    sales_section   JSONB,
    outcome         TEXT,
    recommended_next_action TEXT,
    raw_summary     JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS call_summaries_tenant_customer
    ON call_summaries (tenant_id, customer_id);
"""


class PostCallSummaryRepository(BaseRepository):
    """PostgreSQL-backed repository for post-call sales summaries.

    Schema note: the ``call_summaries`` table is created lazily on first use
    via ``ensure_table()``. The composition root should call this once at
    startup (or the first time any method is called).

    Tenant isolation: every query is scoped by tenant_id (AR-8). The ``get``
    method returns None for a call_id that exists under a different tenant.
    """

    def __init__(self, conn: Any) -> None:
        super().__init__(conn)

    def ensure_table(self) -> None:
        """Create the call_summaries table and index if they do not exist.

        Idempotent — safe to call multiple times (CREATE TABLE IF NOT EXISTS).
        """
        for stmt in _CREATE_TABLE_SQL.split(";"):
            stmt = stmt.strip()
            if stmt:
                self._execute(stmt)
        self._commit()

    def save(
        self,
        call_id: str,
        tenant_id: str,
        customer_id: str,
        summary: dict,
    ) -> None:
        """Persist a post-call summary dict.

        Upserts on call_id — if a summary already exists for this call_id
        (e.g. a retry), it is overwritten. This is intentional: the final
        SalesState at call end is authoritative; a retry should always write
        the latest version.

        Args:
            call_id: The call session identifier (PRIMARY KEY).
            tenant_id: Tenant scope (AR-8).
            customer_id: Authoritative customer identifier.
            summary: The full post-call summary dict from generate_post_call_summary().
        """
        lead = summary.get("lead", {}) or {}
        requirements = summary.get("requirements")
        conversation = summary.get("conversation")
        sales_section = summary.get("sales")

        self._execute(
            f"""
            INSERT INTO {_TABLE} (
                call_id, tenant_id, customer_id,
                lead_stage, lead_temperature, qualification_score,
                requirements, conversation, sales_section,
                outcome, recommended_next_action,
                raw_summary
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (call_id) DO UPDATE SET
                tenant_id = EXCLUDED.tenant_id,
                customer_id = EXCLUDED.customer_id,
                lead_stage = EXCLUDED.lead_stage,
                lead_temperature = EXCLUDED.lead_temperature,
                qualification_score = EXCLUDED.qualification_score,
                requirements = EXCLUDED.requirements,
                conversation = EXCLUDED.conversation,
                sales_section = EXCLUDED.sales_section,
                outcome = EXCLUDED.outcome,
                recommended_next_action = EXCLUDED.recommended_next_action,
                raw_summary = EXCLUDED.raw_summary
            """,
            (
                call_id,
                tenant_id,
                customer_id,
                lead.get("stage"),
                lead.get("temperature"),
                lead.get("qualification_score"),
                json.dumps(requirements) if requirements is not None else None,
                json.dumps(conversation) if conversation is not None else None,
                json.dumps(sales_section) if sales_section is not None else None,
                summary.get("outcome"),
                summary.get("recommended_next_action"),
                json.dumps(summary),
            ),
        )
        self._commit()

    def get(self, call_id: str, tenant_id: str) -> dict | None:
        """Retrieve a post-call summary for a given call_id scoped to tenant_id.

        Returns None if no summary exists for this call_id, or if the
        call_id belongs to a different tenant (tenant isolation — AR-8).

        Args:
            call_id: The call session identifier.
            tenant_id: Tenant scope — only summaries for this tenant are returned.

        Returns:
            The raw_summary dict, or None.
        """
        cur = self._execute(
            f"SELECT raw_summary FROM {_TABLE} WHERE call_id = %s AND tenant_id = %s",
            (call_id, tenant_id),
        )
        row = cur.fetchone()
        if row is None:
            return None
        raw = row[0]
        if isinstance(raw, str):
            return json.loads(raw)
        return raw  # psycopg2 with jsonb returns dict directly
