#!/usr/bin/env bash
# Phase 15 — Staging Environment Setup
# Creates an isolated staging namespace on the production VM using separate
# ports and a dedicated PostgreSQL database (voiceos_staging).
#
# Run as root on the production VM: bash scripts/staging/setup_staging.sh
#
# Services mapped to staging ports:
#   bff.js        :8100  (STAGING_BFF_PORT)
#   web_api       :8101  (STAGING_WEBAPI_PORT)
#   voice runtime :8110  (STAGING_VOICE_PORT)
#   Next.js       :3100  (STAGING_FRONTEND_PORT)
#   Redis         :6479  (separate instance, staging prefix)

set -euo pipefail

STAGING_BFF_PORT="${STAGING_BFF_PORT:-8100}"
STAGING_WEBAPI_PORT="${STAGING_WEBAPI_PORT:-8101}"
STAGING_VOICE_PORT="${STAGING_VOICE_PORT:-8110}"
STAGING_FRONTEND_PORT="${STAGING_FRONTEND_PORT:-3100}"
STAGING_REDIS_PORT="${STAGING_REDIS_PORT:-6479}"
STAGING_DB="voiceos_staging"
STAGING_ENV_FILE="${STAGING_ENV_FILE:-deployment/cpu/.env.staging}"

echo "=== VoiceOS Staging Environment Setup ==="

# ── 1. PostgreSQL staging database ────────────────────────────────────────────
echo "[1/5] Creating staging PostgreSQL database: $STAGING_DB"
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='$STAGING_DB'" | grep -q 1 || \
  sudo -u postgres createdb "$STAGING_DB"
echo "      Applying migrations..."
DATABASE_URL="postgresql://voiceos:$(grep DB_PASSWORD "$STAGING_ENV_FILE" | cut -d= -f2)@localhost/$STAGING_DB" \
  alembic upgrade head
echo "      Done."

# ── 2. Staging Redis instance ──────────────────────────────────────────────────
echo "[2/5] Starting staging Redis on port $STAGING_REDIS_PORT"
if ! systemctl is-active --quiet voiceos-redis-staging 2>/dev/null; then
  redis-server --port "$STAGING_REDIS_PORT" \
               --daemonize yes \
               --logfile /var/log/voiceos/redis-staging.log \
               --save "" \
               --appendonly no
fi
echo "      Done."

# ── 3. Staging env file ────────────────────────────────────────────────────────
echo "[3/5] Writing staging env file: $STAGING_ENV_FILE"
if [[ ! -f "$STAGING_ENV_FILE" ]]; then
  cat > "$STAGING_ENV_FILE" <<EOF
# Staging environment — generated by scripts/staging/setup_staging.sh
NODE_ENV=staging
PORT=$STAGING_BFF_PORT
DATABASE_URL=postgresql://voiceos:CHANGE_ME@localhost/$STAGING_DB
REDIS_URL=redis://localhost:$STAGING_REDIS_PORT
JWT_SECRET=STAGING_JWT_SECRET_$(openssl rand -hex 16)
TWILIO_ACCOUNT_SID=ACtest000000000000000000000000000000
TWILIO_AUTH_TOKEN=STAGING_AUTH_TOKEN
TWILIO_PHONE_NUMBER=+15005550006
COOKIE_DOMAIN=staging.voiceos.local
EOF
  echo "      Created $STAGING_ENV_FILE — fill in real Twilio test creds."
else
  echo "      $STAGING_ENV_FILE already exists, skipping."
fi

# ── 4. Start staging bff.js ────────────────────────────────────────────────────
echo "[4/5] Starting staging bff.js on port $STAGING_BFF_PORT"
if ! pgrep -f "node bff.js.*$STAGING_BFF_PORT" > /dev/null 2>&1; then
  env $(cat "$STAGING_ENV_FILE" | grep -v '^#' | xargs) \
    PORT="$STAGING_BFF_PORT" \
    nohup node bff.js > /var/log/voiceos/bff-staging.log 2>&1 &
  echo "      PID: $!"
else
  echo "      Already running."
fi

# ── 5. Start staging web_api ───────────────────────────────────────────────────
echo "[5/5] Starting staging web_api on port $STAGING_WEBAPI_PORT"
if ! pgrep -f "uvicorn.*$STAGING_WEBAPI_PORT" > /dev/null 2>&1; then
  env $(cat "$STAGING_ENV_FILE" | grep -v '^#' | xargs) \
    nohup uvicorn "src.services.web_api.main:create_app" \
      --factory --host 0.0.0.0 --port "$STAGING_WEBAPI_PORT" \
      > /var/log/voiceos/webapi-staging.log 2>&1 &
  echo "      PID: $!"
else
  echo "      Already running."
fi

echo ""
echo "=== Staging environment ready ==="
echo "    BFF:      http://localhost:$STAGING_BFF_PORT"
echo "    WebAPI:   http://localhost:$STAGING_WEBAPI_PORT"
echo "    Database: $STAGING_DB"
echo "    Redis:    localhost:$STAGING_REDIS_PORT"
echo ""
echo "Run E2E tests: python tests/e2e/test_phase15_staging.py --bff-url http://localhost:$STAGING_BFF_PORT"
