# database module -- managed Postgres (RDS), Multi-AZ (Sprint-026.md, V7 Ch2)
#
# The master password is generated by Terraform (random_password) and stored
# only in AWS Secrets Manager -- never in state as a bare value read path,
# never in a .tfvars file, never hardcoded (CLAUDE.md Security: never expose
# secrets, never hardcode credentials).

resource "random_password" "master" {
  length  = 32
  special = false # RDS master passwords reject a handful of punctuation chars; keep it alphanumeric.
}

resource "aws_secretsmanager_secret" "postgres_master" {
  name        = "${var.name_prefix}-postgres-master"
  description = "RDS Postgres master credential for ${var.name_prefix} (rotate via SecretsManager.SecretRotator, src/libs/secrets/)."
  kms_key_id  = var.kms_key_arn
  tags        = var.tags
}

resource "aws_secretsmanager_secret_version" "postgres_master" {
  secret_id = aws_secretsmanager_secret.postgres_master.id
  secret_string = jsonencode({
    username = "voiceos"
    password = random_password.master.result
  })
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-postgres"
  subnet_ids = var.private_subnet_ids
  tags       = var.tags
}

resource "aws_security_group" "postgres" {
  name_prefix = "${var.name_prefix}-postgres-"
  description = "RDS Postgres -- ingress limited to the EKS node security group only (deny-all default + explicit allow-list)."
  vpc_id      = var.vpc_id

  dynamic "ingress" {
    for_each = var.allowed_security_group_ids
    content {
      description     = "Postgres from EKS nodes"
      from_port       = 5432
      to_port         = 5432
      protocol        = "tcp"
      security_groups = [ingress.value]
    }
  }

  # No egress block: RDS is a managed service that does not need to
  # initiate outbound connections through this ENI -- Terraform's default
  # (no egress block = no egress rules) is the correct, tightest posture
  # here, not a placeholder allow-all (found and fixed running a real
  # `tfsec` scan -- see CHANGELOG.md's Sprint-026 entry).

  tags = merge(var.tags, { Name = "${var.name_prefix}-postgres-sg" })
}

resource "aws_db_instance" "this" {
  identifier     = "${var.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = "15.8"
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage_gb
  max_allocated_storage = var.allocated_storage_gb * 4
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = var.kms_key_arn

  db_name  = "voiceos"
  username = "voiceos"
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [aws_security_group.postgres.id]

  multi_az                = var.multi_az
  backup_retention_period = 7
  # PITR (RPO <= 5 min, Sprint-027 DR validation): automated backups +
  # transaction-log-based point-in-time recovery are enabled by default once
  # backup_retention_period > 0 -- no separate opt-in flag exists on this
  # resource.
  deletion_protection = var.multi_az # production/staging (multi_az=true) get deletion protection; dev doesn't.
  skip_final_snapshot = !var.multi_az

  tags = var.tags
}
